# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarioAdminEgresado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarioAdministradore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEgre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarioAdminEgresado.UsuariosAdminEgresado')),
            ],
        ),
    ]
