# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAdministrador', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuarioAdministradore',
            new_name='UsuarioAdministrador',
        ),
    ]
