# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAdministrador', '0002_auto_20171019_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarioadministrador',
            old_name='userEgre',
            new_name='userAdminEgre',
        ),
    ]
