# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAdministrador', '0003_auto_20171023_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='intereses',
            fields=[
                ('titulo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
