# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAdministrador', '0004_intereses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intereses',
            options={'verbose_name': 'Interes', 'verbose_name_plural': 'Intereses'},
        ),
    ]
