# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAdministrador', '0006_noticias_noticiasintereses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='contenido',
            field=models.TextField(max_length=500),
        ),
    ]
