# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAdministrador', '0007_auto_20171113_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
