# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAdministrador', '0008_auto_20171113_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='noticiasintereses',
            name='interes',
        ),
        migrations.RemoveField(
            model_name='noticiasintereses',
            name='noticia',
        ),
        migrations.DeleteModel(
            name='noticias',
        ),
        migrations.DeleteModel(
            name='noticiasIntereses',
        ),
    ]
