# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAdministrador', '0010_noticias_noticiasintereses'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='fechaCreacion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticias',
            name='fechaEdicion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
