# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAdministrador', '0011_auto_20171118_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='timeCreacion',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticias',
            name='timeEdicion',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
