# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 21:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAdminEgresado', '0002_auto_20171017_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosadminegresado',
            name='DNI',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('[0-9]*', 'prueba.')]),
        ),
    ]
