# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import usuarioAdminEgresado.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAdminEgresado', '0003_auto_20171017_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosadminegresado',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuariosadminegresado',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='usuariosadminegresado',
            name='DNI',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, validators=[usuarioAdminEgresado.models.numeric_validator]),
        ),
    ]
