# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import usuarioAdminEgresado.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAdminEgresado', '0004_auto_20171018_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosadminegresado',
            name='telefono',
            field=models.CharField(max_length=15, validators=[usuarioAdminEgresado.models.numeric_validator]),
        ),
    ]
