# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAdminEgresado', '0007_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='departamentoNombre',
            field=models.CharField(max_length=60),
        ),
    ]
