# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import usuarioAdminEgresado.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAdminEgresado', '0008_auto_20171019_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosadminegresado',
            name='ciudad',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='usuariosadminegresado',
            name='departamento',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='usuariosadminegresado',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuariosadminegresado',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, validators=[usuarioAdminEgresado.models.numeric_validator]),
        ),
    ]
