# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAdminEgresado', '0009_auto_20171021_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosadminegresado',
            name='estadoCuenta',
            field=models.CharField(choices=[('activada', 'Activada'), ('pendiente', 'Pendiente'), ('cerrada', 'Cerrada')], max_length=15),
        ),
    ]
