# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAdminEgresado', '0010_auto_20171025_0759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterField(
            model_name='usuariosadminegresado',
            name='estadoCuenta',
            field=models.CharField(choices=[('activada', 'Activada'), ('pendiente', 'Pendiente'), ('cerrada', 'Cerrada'), ('rechazada', 'Rechazar')], max_length=15),
        ),
    ]
