# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAdminEgresado', '0011_auto_20171101_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='usuariosadminegresado',
            options={'verbose_name': 'Usuario Administrador Egresado', 'verbose_name_plural': 'Usuarios Administradores Egresados'},
        ),
        migrations.RemoveField(
            model_name='usuariosadminegresado',
            name='departamento',
        ),
        migrations.AddField(
            model_name='usuariosadminegresado',
            name='departamento',
            field=models.ManyToManyField(blank=True, null=True, to='usuarioAdminEgresado.Departamento'),
        ),
    ]
