# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAdminEgresado', '0013_auto_20171101_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosadminegresado',
            name='pais',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuariosadminegresado',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
