# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAdminEgresado', '0014_auto_20171103_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariosadminegresado',
            old_name='direccion',
            new_name='direccionResidencia',
        ),
    ]
