# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarioAdminEgresado', '0004_auto_20171018_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosEgresado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=30)),
                ('direccionTrabajo', models.CharField(max_length=100)),
                ('fechaNacimiento', models.DateField()),
                ('genero', models.CharField(max_length=6)),
                ('programa', models.CharField(max_length=100)),
                ('ocupacion', models.CharField(max_length=100)),
                ('userEgre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarioAdminEgresado.UsuariosAdminEgresado')),
            ],
        ),
    ]
