# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioEgresado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='amigosEgresado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(max_length=30)),
                ('amigoDNI', models.CharField(max_length=30)),
            ],
        ),
    ]
