# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioEgresado', '0002_amigosegresado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosegresado',
            name='amigos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarioEgresado.amigosEgresado'),
            preserve_default=False,
        ),
    ]
