# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioEgresado', '0003_usuariosegresado_amigos'),
    ]

    operations = [
        migrations.CreateModel(
            name='interesesEgresado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(max_length=30)),
                ('interesID', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='usuariosegresado',
            name='intereses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarioEgresado.interesesEgresado'),
            preserve_default=False,
        ),
    ]
