# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioEgresado', '0004_auto_20171018_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='amigosegresado',
            name='estado',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
