# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioEgresado', '0005_amigosegresado_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariosegresado',
            name='amigos',
        ),
        migrations.RemoveField(
            model_name='usuariosegresado',
            name='intereses',
        ),
    ]
