# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioEgresado', '0006_auto_20171019_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='amigosegresado',
            name='userEgre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarioEgresado.UsuariosEgresado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interesesegresado',
            name='userEgre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarioEgresado.UsuariosEgresado'),
            preserve_default=False,
        ),
    ]
