# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioEgresado', '0007_auto_20171019_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amigosegresado',
            name='DNI',
        ),
        migrations.RemoveField(
            model_name='interesesegresado',
            name='DNI',
        ),
    ]
