# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioEgresado', '0009_auto_20171019_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosegresado',
            name='direccionTrabajo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuariosegresado',
            name='fechaNacimiento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='usuariosegresado',
            name='genero',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='usuariosegresado',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='usuariosegresado',
            name='pais',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
