# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioEgresado', '0012_auto_20171023_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioegresado',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
