# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioAdministrador', '0004_intereses'),
        ('usuarioEgresado', '0015_auto_20171025_0759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interesesegresado',
            options={'verbose_name': 'Interes de Egresado', 'verbose_name_plural': 'Intereses de egresados'},
        ),
        migrations.RenameField(
            model_name='usuarioegresado',
            old_name='ocupacion',
            new_name='ocupacionActual',
        ),
        migrations.RemoveField(
            model_name='interesesegresado',
            name='interesID',
        ),
        migrations.RemoveField(
            model_name='usuarioegresado',
            name='pais',
        ),
        migrations.AddField(
            model_name='interesesegresado',
            name='interes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarioAdministrador.intereses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarioegresado',
            name='privacidad',
            field=models.CharField(blank=True, choices=[['publico', 'Publico'], ['amigos de amigos', 'Amigos de amigos (tus amigos están incluidos)'], ['amigos', 'Amigos'], ['privado', 'Privado']], max_length=10),
        ),
        migrations.AddField(
            model_name='usuarioegresado',
            name='promoteAge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuarioegresado',
            name='genero',
            field=models.CharField(blank=True, choices=[['masculino', 'Masculino'], ['femenino', 'Femenino'], ['ninguno', 'N/A']], max_length=10),
        ),
    ]
