# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioEgresado', '0017_usuarioegresado_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GraduadosPersonas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('promoteAge', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('estado', models.CharField(choices=[['activo', 'Activo'], ['desactivado', 'Desactivado']], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='graduados',
            name='gradPersonas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarioEgresado.GraduadosPersonas'),
        ),
    ]
