# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioEgresado', '0017_usuarioegresado_fechagraduado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarioegresado',
            old_name='fechaGraduado',
            new_name='promoteAge',
        ),
    ]
