# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioEgresado', '0018_auto_20171105_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioegresado',
            name='isPublico',
            field=models.BooleanField(default=True),
        ),
    ]
