# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioEgresado', '0019_usuarioegresado_ispublico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioegresado',
            name='isPublico',
        ),
        migrations.AddField(
            model_name='usuarioegresado',
            name='privacidad',
            field=models.CharField(blank=True, choices=[['publico', 'Publico'], ['amigos de amigos', 'Amigos de amigos'], ['amigos', 'Amigos'], ['privado', 'Privado']], max_length=10),
        ),
    ]
