# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioEgresado', '0022_auto_20171106_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interesesegresado',
            name='interes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarioAdministrador.intereses'),
        ),
    ]
