# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioEgresado', '0024_auto_20171106_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarioegresado',
            old_name='ocupacion',
            new_name='ocupacionActual',
        ),
    ]
